"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.supabase = void 0;
// This file is automatically generated. Do not edit it directly.
const supabase_js_1 = require("@supabase/supabase-js");
const SUPABASE_URL = "https://bnjthwrpigvchbhsmfec.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJuanRod3JwaWd2Y2hiaHNtZmVjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc1MzE1OTksImV4cCI6MjA3MzEwNzU5OX0.okbuiEqTbdDEbkPFCT1w8-H46UrMHjm-4KXuyQ0PNBU";
// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";
exports.supabase = (0, supabase_js_1.createClient)(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
    auth: {
        storage: localStorage,
        persistSession: true,
        autoRefreshToken: true,
    }
});
