// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bnjthwrpigvchbhsmfec.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJuanRod3JwaWd2Y2hiaHNtZmVjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc1MzE1OTksImV4cCI6MjA3MzEwNzU5OX0.okbuiEqTbdDEbkPFCT1w8-H46UrMHjm-4KXuyQ0PNBU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});